### ISSUE TITLE
`TryFromUByteError(255)` in CRAM parsing

### ISSUE THREAD

**Issue by Euphrasiologist** [zaeleus/noodles#136]
Hi, 

I just can't get my CRAM to parse! And I think here is the culprit:

https://github.com/zaeleus/noodles/blob/16ff2f1a4e296b242ae1b1b623e51c01b03fde92/noodles-sam/src/record/quality_scores/score.rs#L77

I generated a CRAM using this pipeline:

```console
# map synthesised subreads to genome
~/minimap2/minimap2 -a ./drAilAlti1.fa ./fasta_to_map.fa.gz > map.sam
# convert sam to bam
samtools view -T ./drAilAlti1.fa -bS map.sam -o map.bam
# convert bam to cram
samtools view -T ./drAilAlti1.fa -C -o map.cram map.bam
```
And this fails:

```console
cargo run --release --example cram_view ./map.cram ./drAilAlti1.fa
```

I'd love to know why! Been banging my head...

I'll attach the offending files here. Note that the CRAM isn't gzipped (the fasta is), I just renamed it with a gz extension so I could upload onto GitHub.
[map.cram.gz](https://github.com/zaeleus/noodles/files/10094504/map.cram.gz)
[drAilAlti1.fa.gz](https://github.com/zaeleus/noodles/files/10094506/drAilAlti1.fa.gz)

**Comment by zaeleus** [comment]
Thanks for reporting and including an example input!

It seems like CRAM follows the BAM format for `SEQ` and `QUAL` encoding, i.e., "When base qualities are omitted but the sequence is not, `qual` is filled with `0xFF` bytes (to length `l_seq`)."

Decoding in noodles-cram failed because the parser didn't handle missing quality scores like that. A raw quality score of 255 is invalid, so it threw an error.

This is now fixed in 329b16c6e2dabe38a7e60f5aaabe9636b695ff74.
