### ISSUE TITLE
util/variant: Add writer

### ISSUE THREAD

**Issue by zaeleus** [zaeleus/noodles#150]
Add a high-level writer that abstracts writing VCF records in VCF or BCF. It should add a `VariantWriter` trait and be similar to how `util::alignment::Writer` is implemented.

**Comment by malthesr** [comment]
I had a quick look at this. I guess the signature of the `VariantWriter` trait would have to be:

```rust
/// A variant format writer.
pub trait VariantWriter {
    /// Writes a VCF header.
    fn write_variant_header(&mut self, header: &Header) -> io::Result<()>;

    /// Writes a variant record.
    fn write_variant_record(&mut self, header: &Header, string_maps: &StringMaps, record: &Record) -> io::Result<()>;
}
```

Note in particular that `write_variant_record` needs `StringMaps` for the `bcf::Writer` to implement the trait to avoid having to carry out the `From<&vcf::Header>` on each call, which would seem excessive. This in turn means that `VariantWriter` cannot be defined in `noodles-vcf`, as would otherwise be natural, since taking a dependency on `noodles-bcf` for `StringMaps` creates a cycle. I see two options here:

1. Implement `VariantWriter` in `noodles-bcf` and have the impl for both `vcf::Writer` and `bcf::Writer` in `noodles-bcf`. It would then probably also be natural to move `VariantReader` to `noodles-bcf` to have them live together.
2. Move `StringMaps` to `noodles-vcf`, so that `VariantWriter` and the impl for `vcf::Writer` can live there.

Perhaps there's a better option that I'm missing. Do you have any thoughts here?

**Comment by zaeleus** [comment]
I would suggest defining the signature as `fn write_variant_record(&mut self, header: &Header, record: &Record) -> io::Result<()>` and building the dictionary of strings (`StringMaps`) for each BCF record. Yes, this is not efficient, but it will allow you to move forward for now.

There may be a way to hide `StringMaps` entirely from the user, but it's out of the scope for this feature.
