### ISSUE TITLE
Noodle-sam compilation error with two different noodle-bgzf versions

### ISSUE THREAD

**Issue by bio-xy** [zaeleus/noodles#153]
I had this error when compiling with noodles. Not sure what's going on here? How can I just keep v0.14 here and remove v0.15?

![image](https://user-images.githubusercontent.com/13758569/223101420-0fbef0c0-0ca0-4075-bcb4-e2a15af43378.png)
![image](https://user-images.githubusercontent.com/13758569/223101647-eb1aeb40-0f34-4782-9183-29c442deb1b4.png)
![image](https://user-images.githubusercontent.com/13758569/223102019-a8f7ab2d-3cd5-4c58-b113-882417050534.png)

**Comment by zaeleus** [comment]
If you must use noodles 0.26.0, please pin noodles-csi to 0.9.0: `cargo add noodles-csi@=0.9.0`.

**Comment by bio-xy** [comment]
Thanks! It works now. But I am curious why noodles-csi v0.9.1 will cause such err. From the dependency list, I see v0.9.x should work for noodles v0.26.0. Isn't it?
https://crates.io/crates/noodles/0.26.0/dependencies
![image](https://user-images.githubusercontent.com/13758569/223313994-cac6ad88-c46f-4a4a-90a6-7d7006a34af7.png)

**Comment by zaeleus** [comment]
This is unfortunately a mismatch between noodles' versioning scheme and Cargo's semantic versioning compatibility.

[noodles 0.26.0](https://github.com/zaeleus/noodles/blob/ef9cf3a58c1343eb1fb48dbfe183115740bce89d/noodles/CHANGELOG.md#0260---2022-08-16) was released with noodles-bgzf 0.14.0, and [noodles 0.27.0](https://github.com/zaeleus/noodles/blob/ef9cf3a58c1343eb1fb48dbfe183115740bce89d/noodles/CHANGELOG.md#0270---2022-09-29) was released with noodles-bgzf 0.15.0, which triggered a patch release for noodles-csi 0.9.1. While noodles-csi 0.9.0 and 0.9.1 are semver compatable, noodles-bgzf 0.14.0 and 0.15.0 are not! That's why the workaround is to pin to noodles-csi 0.9.0.

Thanks for bringing this issue up, as I'll have to change my assumptions when bumping versions in future releases.
