### ISSUE TITLE
Noodles reports a different offset than the index

### ISSUE THREAD

**Issue by CastilloDel** [zaeleus/noodles#24]
Not sure if this is really wrong, but I thought it could use a revision.
The index (made with [tabix](https://www.htslib.org/doc/tabix.html)) reports a different block offset than noodles. The files can be found [here](https://github.com/umccr/htsget-rs/tree/variants/data/vcf)

Code:
```rust
  let path = std::env::current_dir()
    .unwrap()
    .join("data")
    .join("vcf")
    .join("sample1-bcbio-cancer.vcf.gz");

  let mut reader = File::open(&path)
    .map(bgzf::Reader::new)
    .map(vcf::Reader::new)
    .unwrap();

  println!("From reading the records");
  reader.read_header().unwrap();
  let mut s = String::new();
  loop {
    reader.read_record(&mut s).unwrap();
    if s.is_empty() {
      break;
    }
    let vpos = reader.virtual_position();
    println!("{}/{}", vpos.compressed(), vpos.uncompressed());
    s.clear();
  }

  println!("From the index");
  let index = tabix::read(format!("{}{}", path.to_str().unwrap(), ".tbi")).unwrap();
  index
    .reference_sequences()
    .into_iter()
    .flat_map(|seq| seq.bins())
    .flat_map(|bin| bin.chunks())
    .map(|chunk| chunk.end())
    .for_each(|chunk| println!("{}/{}", chunk.compressed(), chunk.uncompressed()));
```
Output:
```
From reading the records
0/7481
0/7687
0/7882
0/8075
0/8269
0/8463
0/8658
0/8852
0/9108
0/9302
0/9496
3395/0
From the index
0/9302
3367/0
```
The index reports 3367, but noodles reading the records reports 3395.

**Comment by zaeleus** [comment]
Thanks for being patient while iterating through these BGZF position issues. :)

This is a good question. In this particular case, I'd argue noodles is "correct" here.

The way the VCF reader works is by reading the input line-by-line, but the provided input file (`sample1-bcbio-cancer.vcf.gz`) is missing the final newline. When the reader reaches the last line and can't match a line feed (`\n`), it continues to the next block for more data (in this case, the [BGZF EOF block]) and moves the cursor forward. This is where the +28 byte difference comes from. The final block is empty, and the stream also ends.

Interestingly, an index created by GATK 4.2.0.0 (HTSJDK 2.24.0) [IndexFeatureFile] includes the final EOF block like noodles:

```
[...]
From the index
0/9302
3395/0
```

So I'm not quite sure what the expected behavior is supposed to be.

[BGZF EOF block]: https://samtools.github.io/hts-specs/SAMv1.pdf#End-of-file%20marker
[IndexFeatureFile]: https://gatk.broadinstitute.org/hc/en-us/articles/360057441351-IndexFeatureFile

**Comment by CastilloDel** [comment]
Thanks to you for solving them so quickly! 

I didn't know the last `\n` was required 😆. That behaviour makes sense now, so I'll be closing this issue.
