### ISSUE TITLE
BinningIndex query and RangeBounds

### ISSUE THREAD

**Issue by mmalenic** [zaeleus/noodles#32]
I could be missing something, but the `BinningIndex` query function requires a `RangeBounds<i32>` and `Copy` type, however `RangeBounds` does not implement `Copy`. 

Specifically:
 `let chunks = index.query(ref_seq_id, seq_start..=seq_end);`

Outputs error E0277:
`the trait bound RangeInclusive<i32>: std::marker::Copy is not satisfied`

**Comment by zaeleus** [comment]
The generic type for `RangeBounds` has no required constraints. You're creating a `RangeInclusive`, which indeed does not implement `Copy` ([because `Range` types are weird](https://ridiculousfish.com/blog/posts/least-favorite-rust-type.html)). It's now `Clone` (c7b2f522ef37ffa8da84aaeef4a66cfbfd7b135b) to allow `Range` types.

**Comment by mmalenic** [comment]
Thanks @zaeleus !
