### ISSUE TITLE
FASTA reader does not deal with Windows `\r\n` line endings

### ISSUE THREAD

**Issue by slazicoicr** [zaeleus/noodles#5]
Although rare, FASTA files do pass through Windows machines and the current reader assumes `\n` only line endings. 

If this analysis is correct, I am willing to work on it.

**Comment by zaeleus** [comment]
I wouldn't prioritize it since all the other crates in noodles assume Unix(-like) line endings, but if it currently affects you, go for it!

**Comment by slazicoicr** [comment]
I am fine with Unix line endings. Thought of it during the Fasta index PR, as the index can deal with different line endings.

**Comment by d-cameron** [comment]
Sorry to dredge this up (I was looking for release notes for 0.8.0), but from VCFv4.3 onward, both CR and CRLF are explicitly supported as line endings (v4.3 section 1.2). Not a huge issue in practice, but I thought I'd note this as only supporting unix is technically non-compliant with the specifications.

**Comment by zaeleus** [comment]
No problem!

The line ending stringency has relaxed since then. The readers for the text-based formats FASTA (5737caa8f7910617d23b73eb32a327c1db01da26), FASTQ (5e14f183c0cb012cb2fc7ac8505ea9b3312ed24c), GFF (26c344f608440ec39bbbdbe7afd68bafc1884212), SAM (c66dc11b30a6350f1b793a23b410f2934d1a774b), and VCF (eb7774424412aaaa266051d4ab745850b18bff3a) support both line endings (`LF` and `CR LF`) and handle missing final newlines (unexpected EOF).
