### ISSUE TITLE
What is the MSRV

### ISSUE THREAD

**Issue by natir** [zaeleus/noodles#72]
Hello everyone thanks for your very nice work.

I didn't see any information for the Minimal Support Rust Version. This information is important for people use noodles, and for new contributor to know which Rust functionality they can use.

A nice choice for my point of view is use 1.57 Rust version, it's match with edition 2021. But I didn't have many good argument for this version.

**Comment by zaeleus** [comment]
The minimum supported Rust version (MSRV) is 1.56.0 because noodles uses the 2021 edition. It is now defined in each package's manifest using [the `rust-version` field] (9817f7c62ae3483d92f796fd31a2792f354d0395).

[the `rust-version` field]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
