### ISSUE TITLE
bam Readnames end with null terminator

### ISSUE THREAD

**Issue by sstadick** [zaeleus/noodles#8]
Looking at the tests, this is expected and tested for: https://github.com/zaeleus/noodles/blob/0e5af40a786e9b23672552ae8b7ebfc6fd13c460/noodles-bam/src/record.rs#L562

Is it really intentional? That makes the `.read_name()` value really hard to work with.

I noticed this because I am converting from `bam` to `sam` via a sam record builder to modify tag values.

**Comment by sstadick** [comment]
As an aside, is there any way to convert a `bam::record::Record` to a `sam::record::Record` that doesn't involve manually converting via sam record builder?

**Comment by zaeleus** [comment]
Hi, @sstadick!

> Is it really intentional? That makes the .read_name() value really hard to work with.

Yes, it's intentional, but I agree it's currently awkward to handle.

The fields of `bam::Record` are lazily evaluated, and originally, it was up to the caller to perform conversions from the raw data and handle errors. To improve ergonomics, nearly all the fields now have wrappers. I'll likely add one for the read name as well.

> As an aside, is there any way to convert a bam::record::Record to a sam::record::Record that doesn't involve manually converting via sam record builder?

I added a method in cd7e0b30c2e82407250ecedead0356fd08734cc1. Please see [`bam::Record::try_into_sam_record`].

[`bam::Record::try_into_sam_record`]: https://github.com/zaeleus/noodles/blob/cd7e0b30c2e82407250ecedead0356fd08734cc1/noodles-bam/src/record/convert.rs#L25-L28

**Comment by sstadick** [comment]
@zaeleus Thanks for the fast reply! 

That totally makes sense once explained, RE the null terminator. 

Thanks for the conversion method! That is much tidier than what I had going 👍 . 

This is an excellent library and I appreciate all the work you've put into it!
